server:
  port: 8091
#jdbc
spring:
  application:
    name: user-service
  profiles:
    include: conf
  datasource:
    url: jdbc:mysql://rm-uf64qgwq46xmxgd70wo.mysql.rds.aliyuncs.com:3306/core
    username: xsyrdev
    password: Xsyrdev25d
#mybaits
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  # mapper-locations: mapper/*.xml 此处用通用mapper，无需mapper文件
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10089/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    #每隔30s发送一次心跳
    #lease-renewal-interval-in-seconds: 30
    #90s后如果还没有发送心跳就是挂了
    #lease-expiration-duration-in-seconds: 90

