server:
  port: 8098
spring:
  application:
    name: consumer-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10089/eureka
    #每隔多久拉去一次服务列表
    registry-fetch-interval-seconds: 3
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
#feign开启熔断
feign:
  hystrix:
    enabled: true
#ribbon:
  #连接超时时长
  #ConnectionTimeOut: 500
  #读取超时时长
  #ReadTimeOut: 2000
#默认为轮询，自定义负载均衡算法：随机
#user-service:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 3000

