server:
  port: 10086
#给eureka起名
spring:
  application:
    name: eureka-server
#往eureka上注册
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10087/eureka
    #不在启动时注册自己
    register-with-eureka: false
  #失效剔除，30s后会清除所有失效实例
  server:
    eviction-interval-timer-in-ms: 30000

