server:
  port: 10089
#给eureka起名
spring:
  application:
    name: eureka-server
#往eureka上注册
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10089/eureka
    #不在启动时注册自己
    register-with-eureka: false
  #失效剔除，30s后会清除所有失效实例
  server:
    eviction-interval-timer-in-ms: 30000

